In [1]:
import pandas as pd
import numpy as np

- 사용할 feature 정리(2018,2019,2020년 feature가 동일하는 것)

----------------------라이프 로그 데이터----------------------- 

Action: sleep, personal_care, work, study, household, recreation_media, entertainment, outdoor_act, hobby, recreation_etc, communitiy_interaction, travel, meal, socializing

actionSubOption: 1, 2, 3, 4

conditionSub1Option: 1, 2, 3, 4

place: home, workplace, restaurant, outdoor, other_indoor

emotionPositive

emotionTension

activity: 0, 1, 2, 3, 4, 5, 7, 8


-----------------------설문조사 데이터------------------------

sleep: 1, 2, 3, 4, 5

sleepProblem: 0, 1, 2, 3, 4, 5, 6, 7, 8, 9

dream: 1, 2, 3, 4

amEmotion: 1, 2, 3, 4, 5

pmEmotion: 1, 2, 3, 4, 5

pmStress: 1, 2, 3, 4, 5

caffeine

alcohol


--------------------------잠 데이터------------------------

startDt

endDt

sleep_score

total_sleep_time: 2018-2019데이터에는 total_sleep_time으로 되어 있고, 2020년 데이터에는 durationtosleep으로 되어 있음

wakeupcount

# 2020년도와 2018_2019년도 데이터에서 통합할 수 있는 feature들을 통합한 과정임

In [25]:
df_2020 = pd.read_csv('./2020 data/2020_all_data.csv')

df_2020['actionOption_751'] = df_2020[['actionOption_751','actionOption_752','actionOption_753']].sum(axis=1).astype(int)

df_2020['userId'] = '2020_'+df_2020['userId']

#actionOptionSubOption 정리 완료
df_2020['actionSubOption_1'] = df_2020['actionSubOption_move_method_1']
df_2020['actionSubOption_2'] = df_2020['actionSubOption_move_method_2']
df_2020['actionSubOption_3'] = df_2020[['actionSubOption_move_method_3','actionSubOption_move_method_5',
                                        'actionSubOption_move_method_6']].sum(axis=1)
df_2020['actionSubOption_4'] = df_2020['actionSubOption_move_method_4']
df_2020['actionSubOption_5'] = df_2020['actionSubOption_move_method_7']
df_2020 = df_2020.drop(['actionSubOption_move_method_1','actionSubOption_move_method_2',
                       'actionSubOption_move_method_3','actionSubOption_move_method_4',
                       'actionSubOption_move_method_5','actionSubOption_move_method_6',
                       'actionSubOption_move_method_7'], axis=1)

df_2020['conditionSub1Option_5']=df_2020['conditionSub1Option_0']
df_2020 = df_2020.drop(['conditionSub1Option_0'],axis=1)


df_2020['condition_NOT_ALONE'] =  df_2020['condition_WITH_MANY'] + df_2020['condition_WITH_ONE']
df_2020 = df_2020.drop(['condition_WITH_MANY','condition_WITH_ONE'],axis=1)

df_2020

,userId,gender,age,handed,height,weight,startDt_x,endDt_x,date,action_personal_care,...,"('Pre_snoring',)","('Pre_snoringepisodecount',)","('Pre_sleep_score',)","('Pre_date',)",actionSubOption_1,actionSubOption_2,actionSubOption_3,actionSubOption_4,actionSubOption_5,condition_NOT_ALONE
0,2020_user01,0,27,0,167,76,2020-08-30,2020-09-27,2020-08-30,0.0,...,NaN,NaN,NaN,2020-08-29,0.0,120.0,0.0,0.0,0.0,122.0
1,2020_user01,0,27,0,167,76,2020-08-30,2020-09-27,2020-08-31,30.0,...,8880.0,16.0,83.0,2020-08-30,0.0,160.0,0.0,0.0,0.0,180.0
2,2020_user01,0,27,0,167,76,2020-08-30,2020-09-27,2020-09-01,NaN,...,8280.0,16.0,82.0,2020-08-31,NaN,NaN,0.0,NaN,NaN,NaN
3,2020_user01,0,27,0,167,76,2020-08-30,2020-09-27,2020-09-02,NaN,...,8400.0,7.0,53.0,2020-09-01,NaN,NaN,0.0,NaN,NaN,NaN
4,2020_user01,0,27,0,167,76,2020-08-30,2020-09-27,2020-09-03,NaN,...,11400.0,11.0,82.0,2020-09-02,NaN,NaN,0.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
703,2020_user30,0,26,1,174,58,2020-08-31,2020-09-27,2020-09-23,14.0,...,8700.0,13.0,45.0,2020-09-22,63.0,0.0,20.0,0.0,0.0,637.0
704,2020_user30,0,26,1,174,58,2020-08-31,2020-09-27,2020-09-24,13.0,...,10200.0,15.0,56.0,2020-09-23,68.0,0.0,25.0,0.0,0.0,593.0
705,2020_user30,0,26,1,174,58,2020-08-31,2020-09-27,2020-09-25,18.0,...,8940.0,12.0,56.0,2020-09-24,68.0,0.0,25.0,0.0,0.0,521.0
706,2020_user30,0,26,1,174,58,2020-08-31,2020-09-27,2020-09-26,10.0,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0
707,2020_user30,0,26,1,174,58,2020-08-31,2020-09-27,2020-09-27,30.0,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0

In [26]:
df_2018_2019 = pd.read_csv('./2018-2019 data/2018-2019_all_data.csv')

df_2018_2019['userId'] = '2018_2019_'+df_2018_2019['userId']


#actionOption 정리 완료
df_2018_2019['actionOption_751']=df_2018_2019[['actionOption_0','actionOption_1', 'actionOption_2','actionOption_6']].sum(axis=1).astype(int)
df_2018_2019['actionOption_793']=df_2018_2019[['actionOption_4','actionOption_5']].sum(axis=1).astype(int)
df_2018_2019=df_2018_2019.drop(['actionOption_0','actionOption_1','actionOption_2','actionOption_3',
                               'actionOption_4','actionOption_5','actionOption_6'],axis=1)

#actionOptionSubOption 정리 완료
df_2018_2019['actionSubOption_5']=df_2018_2019['actionSubOption_0']
df_2018_2019 = df_2018_2019.drop(['actionSubOption_0'],axis=1)

#conditionSub1Option 정리 완료
df_2018_2019['conditionSub1Option_5']=df_2018_2019['condition_0']

df_2018_2019['condition_ALONE'] = df_2018_2019['condition_0']
df_2018_2019['condition_NOT_ALONE'] = df_2018_2019['condition_1'] + df_2018_2019['condition_2'] + df_2018_2019['condition_3'] + df_2018_2019['condition_4']
df_2018_2019 = df_2018_2019.drop(['condition_0','condition_1','condition_2','condition_3','condition_4'],axis=1)

df_2018_2019

,userId,gender,age,height,weight,startDt_x,endDt_x,date,action_personal_care,action_sleep,...,"('Pre_movement_index',)","('Pre_fragmentation_index',)","('Pre_sleep_frag_index',)","('Pre_date',)",actionOption_751,actionOption_793,actionSubOption_5,conditionSub1Option_5,condition_ALONE,condition_NOT_ALONE
0,2018_2019_user1,M,24,NaN,NaN,2018-11-15,2018-11-28,2018-11-15,0.0,0.0,...,NaN,NaN,NaN,2018-11-14,48,95,0.0,0.0,0.0,651.0
1,2018_2019_user1,M,24,NaN,NaN,2018-11-15,2018-11-28,2018-11-16,0.0,65.0,...,NaN,NaN,NaN,2018-11-15,53,65,0.0,83.0,83.0,750.0
2,2018_2019_user1,M,24,NaN,NaN,2018-11-15,2018-11-28,2018-11-17,19.0,35.0,...,NaN,NaN,NaN,2018-11-16,57,397,0.0,424.0,424.0,203.0
3,2018_2019_user1,M,24,NaN,NaN,2018-11-15,2018-11-28,2018-11-18,58.0,134.0,...,NaN,NaN,NaN,2018-11-17,54,367,0.0,421.0,421.0,308.0
4,2018_2019_user1,M,24,NaN,NaN,2018-11-15,2018-11-28,2018-11-19,0.0,58.0,...,NaN,NaN,NaN,2018-11-18,52,58,0.0,58.0,58.0,703.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
973,2018_2019_user9,F,42,NaN,NaN,2018-10-31,2018-11-13,2018-11-09,32.0,0.0,...,NaN,NaN,NaN,2018-11-08,190,0,0.0,209.0,209.0,401.0
974,2018_2019_user9,F,42,NaN,NaN,2018-10-31,2018-11-13,2018-11-10,71.0,0.0,...,NaN,NaN,NaN,2018-11-09,238,256,0.0,439.0,439.0,312.0
975,2018_2019_user9,F,42,NaN,NaN,2018-10-31,2018-11-13,2018-11-11,104.0,0.0,...,NaN,NaN,NaN,2018-11-10,229,173,42.0,134.0,134.0,596.0
976,2018_2019_user9,F,42,NaN,NaN,2018-10-31,2018-11-13,2018-11-12,64.0,0.0,...,NaN,NaN,NaN,2018-11-11,169,39,0.0,231.0,231.0,396.0
977,2018_2019_user9,F,42,NaN,NaN,2018-10-31,2018-11-13,2018-11-13,59.0,0.0,...,NaN,NaN,NaN,NaN,322,24,0.0,190.0,190.0,477.0

# 2018-2019, 2020년도 데이터를 feature 상관없이 통합한 과정

In [27]:
df = pd.concat([df_2018_2019,df_2020])

In [28]:
df

,userId,gender,age,height,weight,startDt_x,endDt_x,date,action_personal_care,action_sleep,...,"('Pre_durationtowakeup',)","('Pre_hr_average',)","('Pre_hr_min',)","('Pre_hr_max',)","('Pre_rr_average',)","('Pre_rr_min',)","('Pre_rr_max',)","('Pre_breathing_disturbances_intensity',)","('Pre_snoring',)","('Pre_snoringepisodecount',)"
0,2018_2019_user1,M,24,NaN,NaN,2018-11-15,2018-11-28,2018-11-15,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2018_2019_user1,M,24,NaN,NaN,2018-11-15,2018-11-28,2018-11-16,0.0,65.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2018_2019_user1,M,24,NaN,NaN,2018-11-15,2018-11-28,2018-11-17,19.0,35.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2018_2019_user1,M,24,NaN,NaN,2018-11-15,2018-11-28,2018-11-18,58.0,134.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2018_2019_user1,M,24,NaN,NaN,2018-11-15,2018-11-28,2018-11-19,0.0,58.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
703,2020_user30,0,26,174.0,58.0,2020-08-31,2020-09-27,2020-09-23,14.0,0.0,...,0.0,64.0,52.0,84.0,15.0,10.0,21.0,24.0,8700.0,13.0
704,2020_user30,0,26,174.0,58.0,2020-08-31,2020-09-27,2020-09-24,13.0,0.0,...,0.0,63.0,52.0,84.0,14.0,10.0,21.0,22.0,10200.0,15.0
705,2020_user30,0,26,174.0,58.0,2020-08-31,2020-09-27,2020-09-25,18.0,0.0,...,0.0,62.0,52.0,79.0,15.0,9.0,23.0,17.0,8940.0,12.0
706,2020_user30,0,26,174.0,58.0,2020-08-31,2020-09-27,2020-09-26,10.0,86.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
707,2020_user30,0,26,174.0,58.0,2020-08-31,2020-09-27,2020-09-27,30.0,113.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# 통합된 데이터 csv 파일로 저장

In [29]:
df.to_csv('./complete_data.csv',index=False)